[project]
name = "pythonproject2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "fastmcp[standard]>=2.14.4",
    "google-api-python-client>=2.189.0",
    "google-auth>=2.48.0",
    "google-auth-oauthlib>=1.2.4",
    "httpx>=0.28.1",
    "langgraph>=1.0.7",
    "openai>=2.15.0",
    "pdfminer-six>=20260107",
    "psycopg2>=2.9.11",
    "pydantic>=2.12.5",
    "youtube-transcript-api>=1.2.3",
]
